name: Bump Version/Push Tag

on:
  push:
    branches:
      - master

jobs:
  bump_tag:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Bump version/Push new tag
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN:     ${{ secrets.GITHUB_TOKEN }}
          WITH_V:           true
          RELEASE_BRANCHES: master